//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreSolution.WebProject.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoreSolution.WebProject.App_GlobalResources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Basket_BuyButton {
            get {
                return ResourceManager.GetString("Basket_BuyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your basket is empty..
        /// </summary>
        public static string Basket_EmptyOrder {
            get {
                return ResourceManager.GetString("Basket_EmptyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Basket_HeaderCount {
            get {
                return ResourceManager.GetString("Basket_HeaderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Basket_HeaderName {
            get {
                return ResourceManager.GetString("Basket_HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Basket_HeaderPrice {
            get {
                return ResourceManager.GetString("Basket_HeaderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price.
        /// </summary>
        public static string Basket_HeaderTotalPrice {
            get {
                return ResourceManager.GetString("Basket_HeaderTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order.
        /// </summary>
        public static string Basket_Title {
            get {
                return ResourceManager.GetString("Basket_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0:c}.
        /// </summary>
        public static string Basket_Total {
            get {
                return ResourceManager.GetString("Basket_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! Nice to see You here. Please sign in to shop..
        /// </summary>
        public static string Index_Header {
            get {
                return ResourceManager.GetString("Index_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Index_Login {
            get {
                return ResourceManager.GetString("Index_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Index_LoginButon {
            get {
                return ResourceManager.GetString("Index_LoginButon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not registered yet?.
        /// </summary>
        public static string Index_NewUser {
            get {
                return ResourceManager.GetString("Index_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Index_Password {
            get {
                return ResourceManager.GetString("Index_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully user creation.
        /// </summary>
        public static string Index_SuccessfullyUserCreation {
            get {
                return ResourceManager.GetString("Index_SuccessfullyUserCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Your Store!.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials are wrong.
        /// </summary>
        public static string Index_ValidateError {
            get {
                return ResourceManager.GetString("Index_ValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Master_BackButton {
            get {
                return ResourceManager.GetString("Master_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string Master_SignOutButton {
            get {
                return ResourceManager.GetString("Master_SignOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good day, {0}!.
        /// </summary>
        public static string Master_ToProfile {
            get {
                return ResourceManager.GetString("Master_ToProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string NewUser_Answer {
            get {
                return ResourceManager.GetString("NewUser_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string NewUser_BackButton {
            get {
                return ResourceManager.GetString("NewUser_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error create new user..
        /// </summary>
        public static string NewUser_CreateUserError {
            get {
                return ResourceManager.GetString("NewUser_CreateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string NewUser_Email {
            get {
                return ResourceManager.GetString("NewUser_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fields are emprty..
        /// </summary>
        public static string NewUser_EmptyFieldsError {
            get {
                return ResourceManager.GetString("NewUser_EmptyFieldsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your credentials.
        /// </summary>
        public static string NewUser_Header {
            get {
                return ResourceManager.GetString("NewUser_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string NewUser_Login {
            get {
                return ResourceManager.GetString("NewUser_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login must have only letters, numbers and underscopes. First symbol must be letter. Length must be more than 5 symbols..
        /// </summary>
        public static string NewUser_LoginError {
            get {
                return ResourceManager.GetString("NewUser_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string NewUser_Password {
            get {
                return ResourceManager.GetString("NewUser_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have letters, numbers and symbols: _,!,@,#,$,%,^,&amp;,*. First symbol must be letter. Length must be more than 5 symbols..
        /// </summary>
        public static string NewUser_PasswordError {
            get {
                return ResourceManager.GetString("NewUser_PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string NewUser_Question {
            get {
                return ResourceManager.GetString("NewUser_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string NewUser_SubmitButton {
            get {
                return ResourceManager.GetString("NewUser_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string NewUser_Title {
            get {
                return ResourceManager.GetString("NewUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to busket.
        /// </summary>
        public static string ProductCatalog_BusketButton {
            get {
                return ResourceManager.GetString("ProductCatalog_BusketButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose products for youself!.
        /// </summary>
        public static string ProductCatalog_Header {
            get {
                return ResourceManager.GetString("ProductCatalog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ProductCatalog_HeaderCategory {
            get {
                return ResourceManager.GetString("ProductCatalog_HeaderCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string ProductCatalog_HeaderCount {
            get {
                return ResourceManager.GetString("ProductCatalog_HeaderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProductCatalog_HeaderName {
            get {
                return ResourceManager.GetString("ProductCatalog_HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string ProductCatalog_HeaderPrice {
            get {
                return ResourceManager.GetString("ProductCatalog_HeaderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product {0} was added to order..
        /// </summary>
        public static string ProductCatalog_ProductAdded {
            get {
                return ResourceManager.GetString("ProductCatalog_ProductAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product {0} was removed from order..
        /// </summary>
        public static string ProductCatalog_ProductRemoved {
            get {
                return ResourceManager.GetString("ProductCatalog_ProductRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products were bought successfully..
        /// </summary>
        public static string ProductCatalog_ProductsBought {
            get {
                return ResourceManager.GetString("ProductCatalog_ProductsBought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product catalog.
        /// </summary>
        public static string ProductCatalog_Title {
            get {
                return ResourceManager.GetString("ProductCatalog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ProductManagement_DeleteButton {
            get {
                return ResourceManager.GetString("ProductManagement_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ProductManagement_EditButton {
            get {
                return ResourceManager.GetString("ProductManagement_EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ProductManagement_HeaderCategory {
            get {
                return ResourceManager.GetString("ProductManagement_HeaderCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ProductManagement_HeaderId {
            get {
                return ResourceManager.GetString("ProductManagement_HeaderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProductManagement_HeaderName {
            get {
                return ResourceManager.GetString("ProductManagement_HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string ProductManagement_HeaderPrice {
            get {
                return ResourceManager.GetString("ProductManagement_HeaderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ProductManagement_InsertAnswerNo {
            get {
                return ResourceManager.GetString("ProductManagement_InsertAnswerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ProductManagement_InsertAnswerYes {
            get {
                return ResourceManager.GetString("ProductManagement_InsertAnswerYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string ProductManagement_InsertButton {
            get {
                return ResourceManager.GetString("ProductManagement_InsertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue?.
        /// </summary>
        public static string ProductManagement_InsertQuestion {
            get {
                return ResourceManager.GetString("ProductManagement_InsertQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product successfully added..
        /// </summary>
        public static string ProductManagement_ProductWasAdded {
            get {
                return ResourceManager.GetString("ProductManagement_ProductWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product wasn&apos;t added..
        /// </summary>
        public static string ProductManagement_ProductWasNotAdded {
            get {
                return ResourceManager.GetString("ProductManagement_ProductWasNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product wasn&apos;t removed..
        /// </summary>
        public static string ProductManagement_ProductWasNotRemoved {
            get {
                return ResourceManager.GetString("ProductManagement_ProductWasNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product wasn&apos;t updated. Not valid value. Please check entered values..
        /// </summary>
        public static string ProductManagement_ProductWasNotUpdated {
            get {
                return ResourceManager.GetString("ProductManagement_ProductWasNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product was removed..
        /// </summary>
        public static string ProductManagement_ProductWasRemoved {
            get {
                return ResourceManager.GetString("ProductManagement_ProductWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product successfully updated..
        /// </summary>
        public static string ProductManagement_ProductWasUpdated {
            get {
                return ResourceManager.GetString("ProductManagement_ProductWasUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product management.
        /// </summary>
        public static string ProductManagement_Title {
            get {
                return ResourceManager.GetString("ProductManagement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter both passwords..
        /// </summary>
        public static string Profile_BothPasswordsError {
            get {
                return ResourceManager.GetString("Profile_BothPasswordsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Profile_ChangeButton {
            get {
                return ResourceManager.GetString("Profile_ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Profile_ChangePassword {
            get {
                return ResourceManager.GetString("Profile_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load choosen icon.
        /// </summary>
        public static string Profile_CommitIcon {
            get {
                return ResourceManager.GetString("Profile_CommitIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Profile_ExitButton {
            get {
                return ResourceManager.GetString("Profile_ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon  successfully changed..
        /// </summary>
        public static string Profile_IconWasChanged {
            get {
                return ResourceManager.GetString("Profile_IconWasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon wasn&apos;t changed..
        /// </summary>
        public static string Profile_IconWasNotChanged {
            get {
                return ResourceManager.GetString("Profile_IconWasNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Profile_NewPassword {
            get {
                return ResourceManager.GetString("Profile_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing changed. Try again..
        /// </summary>
        public static string Profile_NothingChanged {
            get {
                return ResourceManager.GetString("Profile_NothingChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file was not choosen..
        /// </summary>
        public static string Profile_NotImage {
            get {
                return ResourceManager.GetString("Profile_NotImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only .Jpg image files allowed..
        /// </summary>
        public static string Profile_NotJpg {
            get {
                return ResourceManager.GetString("Profile_NotJpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string Profile_OldPassword {
            get {
                return ResourceManager.GetString("Profile_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have letters, numbers and symbols: _,!,@,#,$,%,^,&amp;,*. First symbol must be letter. Length must be more than 5 symbols..
        /// </summary>
        public static string Profile_PasswordError {
            get {
                return ResourceManager.GetString("Profile_PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Password successfully changed..
        /// </summary>
        public static string Profile_PasswordWasChanged {
            get {
                return ResourceManager.GetString("Profile_PasswordWasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        public static string Profile_PersonalData {
            get {
                return ResourceManager.GetString("Profile_PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new personal data successfully changed..
        /// </summary>
        public static string Profile_PersonalDataChanged {
            get {
                return ResourceManager.GetString("Profile_PersonalDataChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Profile_PersonalName {
            get {
                return ResourceManager.GetString("Profile_PersonalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second name.
        /// </summary>
        public static string Profile_PersonalSecondName {
            get {
                return ResourceManager.GetString("Profile_PersonalSecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Profile_SubmitButton {
            get {
                return ResourceManager.GetString("Profile_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
    }
}
